name: "Diff Size"
description: Adds a label to each pull request based on the number of lines changed.

inputs:
  xs-threshold:
    description: "The maximum number of lines changed for an extra small label to be assigned (default: 10)."
    required: true
    default: "10"
  s-threshold:
    description: "The maximum number of lines changed for a small label to be assigned (default: 100)."
    required: true
    default: "100"
  m-threshold:
    description: "The maximum number of lines changed for a medium label to be assigned (default: 200)."
    required: true
    default: "200"
  l-threshold:
    description: "The maximum number of lines changed for a large label to be assigned (default: 400)."
    required: true
    default: "400"
  xl-threshold:
    description: "The maximum number of lines changed for a extra large label to be assigned (default: 800)."
    required: true
    default: "800"
  xs-label:
    description: "The name of the label for very small number of lines changed."
    required: true
    default: "size/XS"
  s-label:
    description: "The name of the label for small number of lines changed."
    required: true
    default: "size/S"
  m-label:
    description: "The name of the label for medium number of lines changed."
    required: true
    default: "size/M"
  l-label:
    description: "The name of the label for large number of lines changed."
    required: true
    default: "size/L"
  xl-label:
    description: "The name of the label for very large number of lines changed."
    required: true
    default: "size/XL"
  xxl-label:
    description: "The name of the label for very, very large number of lines changed."
    required: true
    default: "size/XXL"

outputs:
  label:
    description: "The label assigned to the pull request."
  size:
    description: "The calculated size of the pull request's changes."
  includes:
    description: "The files included in the size calculation."
  excludes:
    description: "The files excluded from the size calculation."

runs:
  using: "node20"
  main: "index.js"
